# Generated by Django 3.0 on 2022-03-01 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('state_id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('testimonial_id', models.AutoField(primary_key=True, serialize=False)),
                ('photo', models.ImageField(upload_to='')),
                ('review_text', models.TextField()),
                ('signature', models.CharField(max_length=128)),
                ('designation', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('district_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('state_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routersNetworkHtmlPages.State')),
            ],
        ),
    ]
