# Generated by Django 3.0 on 2022-03-24 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('routersNetworkHtmlPages', '0002_auto_20220314_0107'),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('query_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=512)),
                ('company_name', models.CharField(max_length=512)),
                ('state', models.CharField(max_length=64)),
                ('district', models.CharField(max_length=512)),
                ('pincode', models.CharField(max_length=6)),
                ('contact', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=512)),
                ('license', models.CharField(max_length=100)),
                ('query_msg', models.TextField()),
                ('date', models.DateField(auto_now=True)),
                ('time', models.TimeField(auto_now=True)),
                ('query_assign_by_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_assign', to=settings.AUTH_USER_MODEL)),
                ('query_assign_to_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_given', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
