# Generated by Django 3.0 on 2022-04-03 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routersNetworkHtmlPages', '0004_auto_20220324_1724'),
    ]

    operations = [
        migrations.CreateModel(
            name='DOT',
            fields=[
                ('news_id', models.AutoField(primary_key=True, serialize=False)),
                ('news_title', models.CharField(max_length=64)),
                ('news_discription', models.TextField()),
                ('pdf', models.FileField(upload_to='news')),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('time', models.TimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
