# Generated by Django 3.2.7 on 2021-09-24 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_form_details',
            name='is_contacted',
            field=models.BooleanField(default=False),
        ),
    ]
