# Generated by Django 4.0 on 2022-04-03 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contact_form_details_is_contacted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_form_details',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
