# Generated by Django 3.0 on 2022-04-03 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_alter_contact_form_details_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_form_details',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
